### ISSUE TITLE
Check camera_projection logic and reuse astrobee_fsw code when possible

### ISSUE THREAD

**Issue by marinagmoreira** [nasa/isaac#71]
My biggest concern here is that I couldn't figure out where this function handles the camera distortion. And I think instead of trying to reinvent this logic, we should use some existing functions:
- https://github.com/nasa/astrobee/blob/1a0b93a73d6dcfe932da127d2678724e0f9aa542/localization/camera/include/camera/camera_model.h#L45 - Convert from 3D point to UNDISTORTED_C 2D
- Compare to undistorted half-width to check if in FOV per Oleg's comment
- https://github.com/nasa/astrobee/blob/1a0b93a73d6dcfe932da127d2678724e0f9aa542/localization/camera/include/camera/camera_params.h#L178 - Convert from UNDISTORTED_C to DISTORTED

(Ryan and Oleg are the experts on this. My concern is that the math is tricky and we want to consistently use the well-tested implementation. And even if we use the existing implementation, I would still be a bit concerned about possible corner cases in checking whether the point is within the FOV, things like math blowing up if the point is right behind the camera. Ryan has thought about that kind of thing a lot.)

Less critical issues:

Logically, the outputs from this function could be floating point pixel coordinates. Not sure why we are forcing them to be rounded to an integer. That could be up to whoever is using the function. Like if they have an image and want to look up the value at the resulting XY position, they could choose to round to the nearest integer and use that pixel value (nearest neighbor lookup), or they could do something more sophisticated like interpolating using the surrounding pixel values.

It would be easier to understand if the function returned an `Eigen::Vector2D` (or similar) rather than using reference arguments as outputs. If an error is possible, it could return a `std::optional<Eigen::Vector2D>` with an error represented by an empty value (which is nice because any attempt to use the empty value will cause a run-time error). https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs

_Originally posted by @trey0 in https://github.com/nasa/isaac/pull/70#discussion_r1060660878_

**Comment by trey0** [comment]
Hm. The plan above was a bit off. Addressing your comment and Oleg's at https://github.com/nasa/isaac/pull/91#discussion_r1196699834 . I should have said:

- https://github.com/nasa/astrobee/blob/1a0b93a73d6dcfe932da127d2678724e0f9aa542/localization/camera/include/camera/camera_model.h#L45 - Convert from 3D point to UNDISTORTED_C 2D
- https://github.com/nasa/astrobee/blob/1a0b93a73d6dcfe932da127d2678724e0f9aa542/localization/camera/include/camera/camera_params.h#L178 - Convert from UNDISTORTED_C to DISTORTED
- Compare to distorted half-size as in the later part of `IsInFov()`, but now the comparison is correct because we are comparing to distorted coordinates. https://github.com/nasa/astrobee/blob/1a0b93a73d6dcfe932da127d2678724e0f9aa542/localization/camera/src/camera_model.cc#L114
